# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'App.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppFrame(object):
    def setupUi(self, AppFrame):
        AppFrame.setObjectName("AppFrame")
        AppFrame.resize(495, 495)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AppFrame.sizePolicy().hasHeightForWidth())
        AppFrame.setSizePolicy(sizePolicy)
        AppFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        AppFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.layoutWidget = QtWidgets.QWidget(AppFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 15, 489, 473))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grdLayout = QtWidgets.QGridLayout()
        self.grdLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.grdLayout.setContentsMargins(-1, 0, -1, -1)
        self.grdLayout.setSpacing(6)
        self.grdLayout.setObjectName("grdLayout")
        self.l_mx = QtWidgets.QLabel(self.layoutWidget)
        self.l_mx.setObjectName("l_mx")
        self.grdLayout.addWidget(self.l_mx, 1, 0, 1, 1)
        self.l_lx = QtWidgets.QLabel(self.layoutWidget)
        self.l_lx.setObjectName("l_lx")
        self.grdLayout.addWidget(self.l_lx, 3, 0, 1, 1)
        self.l_n = QtWidgets.QLabel(self.layoutWidget)
        self.l_n.setObjectName("l_n")
        self.grdLayout.addWidget(self.l_n, 0, 0, 1, 1)
        self.l_my = QtWidgets.QLabel(self.layoutWidget)
        self.l_my.setObjectName("l_my")
        self.grdLayout.addWidget(self.l_my, 2, 0, 1, 1)
        self.l_ly = QtWidgets.QLabel(self.layoutWidget)
        self.l_ly.setObjectName("l_ly")
        self.grdLayout.addWidget(self.l_ly, 4, 0, 1, 1)
        self.te_ly = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.te_ly.setAutoFillBackground(False)
        self.te_ly.setStyleSheet("")
        self.te_ly.setWrapping(False)
        self.te_ly.setFrame(True)
        self.te_ly.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.te_ly.setPrefix("")
        self.te_ly.setMaximum(5000.0)
        self.te_ly.setObjectName("te_ly")
        self.grdLayout.addWidget(self.te_ly, 4, 1, 1, 1)
        self.te_n = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.te_n.setBaseSize(QtCore.QSize(0, 0))
        self.te_n.setAutoFillBackground(False)
        self.te_n.setStyleSheet("")
        self.te_n.setWrapping(False)
        self.te_n.setFrame(True)
        self.te_n.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.te_n.setPrefix("")
        self.te_n.setMaximum(100000.0)
        self.te_n.setObjectName("te_n")
        self.grdLayout.addWidget(self.te_n, 0, 1, 1, 1)
        self.te_mx = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.te_mx.setAutoFillBackground(False)
        self.te_mx.setStyleSheet("")
        self.te_mx.setWrapping(False)
        self.te_mx.setFrame(True)
        self.te_mx.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.te_mx.setPrefix("")
        self.te_mx.setMinimum(-100000.0)
        self.te_mx.setMaximum(100000.0)
        self.te_mx.setSingleStep(0.1)
        self.te_mx.setObjectName("te_mx")
        self.grdLayout.addWidget(self.te_mx, 1, 1, 1, 1)
        self.te_my = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.te_my.setAutoFillBackground(False)
        self.te_my.setStyleSheet("")
        self.te_my.setWrapping(False)
        self.te_my.setFrame(True)
        self.te_my.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.te_my.setPrefix("")
        self.te_my.setMinimum(-100000.0)
        self.te_my.setMaximum(100000.0)
        self.te_my.setSingleStep(0.1)
        self.te_my.setObjectName("te_my")
        self.grdLayout.addWidget(self.te_my, 2, 1, 1, 1)
        self.te_lx = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.te_lx.setAutoFillBackground(False)
        self.te_lx.setStyleSheet("")
        self.te_lx.setWrapping(False)
        self.te_lx.setFrame(True)
        self.te_lx.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.te_lx.setPrefix("")
        self.te_lx.setMaximum(5000.0)
        self.te_lx.setObjectName("te_lx")
        self.grdLayout.addWidget(self.te_lx, 3, 1, 1, 1)
        self.l_y = QtWidgets.QLabel(self.layoutWidget)
        self.l_y.setObjectName("l_y")
        self.grdLayout.addWidget(self.l_y, 7, 0, 1, 1)
        self.l_x = QtWidgets.QLabel(self.layoutWidget)
        self.l_x.setObjectName("l_x")
        self.grdLayout.addWidget(self.l_x, 6, 0, 1, 1)
        self.l_xy_ger = QtWidgets.QLabel(self.layoutWidget)
        self.l_xy_ger.setObjectName("l_xy_ger")
        self.grdLayout.addWidget(self.l_xy_ger, 8, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.grdLayout.addWidget(self.line, 5, 0, 1, 2)
        self.btn_ger_xy_hesapla = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_ger_xy_hesapla.setObjectName("btn_ger_xy_hesapla")
        self.grdLayout.addWidget(self.btn_ger_xy_hesapla, 9, 0, 1, 2)
        self.te_x = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.te_x.setAutoFillBackground(False)
        self.te_x.setStyleSheet("")
        self.te_x.setWrapping(False)
        self.te_x.setFrame(True)
        self.te_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.te_x.setPrefix("")
        self.te_x.setMinimum(-5000.0)
        self.te_x.setMaximum(5000.0)
        self.te_x.setSingleStep(0.1)
        self.te_x.setObjectName("te_x")
        self.grdLayout.addWidget(self.te_x, 6, 1, 1, 1)
        self.te_xy_ger = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.te_xy_ger.setAutoFillBackground(False)
        self.te_xy_ger.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.te_xy_ger.setWrapping(False)
        self.te_xy_ger.setFrame(True)
        self.te_xy_ger.setReadOnly(True)
        self.te_xy_ger.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.te_xy_ger.setPrefix("")
        self.te_xy_ger.setDecimals(4)
        self.te_xy_ger.setMaximum(5000.0)
        self.te_xy_ger.setObjectName("te_xy_ger")
        self.grdLayout.addWidget(self.te_xy_ger, 8, 1, 1, 1)
        self.te_y = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.te_y.setAutoFillBackground(False)
        self.te_y.setStyleSheet("")
        self.te_y.setWrapping(False)
        self.te_y.setFrame(True)
        self.te_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.te_y.setPrefix("")
        self.te_y.setMinimum(-5000.0)
        self.te_y.setMaximum(5000.0)
        self.te_y.setSingleStep(0.1)
        self.te_y.setObjectName("te_y")
        self.grdLayout.addWidget(self.te_y, 7, 1, 1, 1)
        self.horizontalLayout.addLayout(self.grdLayout)
        self.figure = QtWidgets.QLabel(self.layoutWidget)
        self.figure.setMinimumSize(QtCore.QSize(320, 0))
        self.figure.setStyleSheet("background: white")
        self.figure.setFrameShape(QtWidgets.QFrame.Box)
        self.figure.setFrameShadow(QtWidgets.QFrame.Plain)
        self.figure.setText("")
        self.figure.setObjectName("figure")
        self.horizontalLayout.addWidget(self.figure)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.te_result = QtWidgets.QTextEdit(self.layoutWidget)
        self.te_result.setObjectName("te_result")
        self.verticalLayout.addWidget(self.te_result)
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btnHesapla = QtWidgets.QPushButton(self.splitter)
        self.btnHesapla.setObjectName("btnHesapla")
        self.btnDosyadanHesapla = QtWidgets.QPushButton(self.splitter)
        self.btnDosyadanHesapla.setObjectName("btnDosyadanHesapla")
        self.btnYardim = QtWidgets.QPushButton(self.splitter)
        self.btnYardim.setObjectName("btnYardim")
        self.btnExit = QtWidgets.QPushButton(self.splitter)
        self.btnExit.setObjectName("btnExit")
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(AppFrame)
        self.btnExit.clicked.connect(AppFrame.close)
        QtCore.QMetaObject.connectSlotsByName(AppFrame)
        AppFrame.setTabOrder(self.te_n, self.te_mx)
        AppFrame.setTabOrder(self.te_mx, self.te_my)
        AppFrame.setTabOrder(self.te_my, self.te_lx)
        AppFrame.setTabOrder(self.te_lx, self.te_ly)
        AppFrame.setTabOrder(self.te_ly, self.te_x)
        AppFrame.setTabOrder(self.te_x, self.te_y)
        AppFrame.setTabOrder(self.te_y, self.te_xy_ger)
        AppFrame.setTabOrder(self.te_xy_ger, self.btn_ger_xy_hesapla)
        AppFrame.setTabOrder(self.btn_ger_xy_hesapla, self.te_result)
        AppFrame.setTabOrder(self.te_result, self.btnHesapla)
        AppFrame.setTabOrder(self.btnHesapla, self.btnDosyadanHesapla)
        AppFrame.setTabOrder(self.btnDosyadanHesapla, self.btnYardim)
        AppFrame.setTabOrder(self.btnYardim, self.btnExit)

    def retranslateUi(self, AppFrame):
        _translate = QtCore.QCoreApplication.translate
        AppFrame.setWindowTitle(_translate("AppFrame", "Dikdörtgen Temellerde Zemin Gerilme Hesabı"))
        self.l_mx.setText(_translate("AppFrame", "Mx (tm)"))
        self.l_lx.setText(_translate("AppFrame", "Lx (m)"))
        self.l_n.setText(_translate("AppFrame", "N (t)"))
        self.l_my.setText(_translate("AppFrame", "My (tm)"))
        self.l_ly.setText(_translate("AppFrame", "Ly (m)"))
        self.te_ly.setSuffix(_translate("AppFrame", " m"))
        self.te_n.setSuffix(_translate("AppFrame", " t"))
        self.te_mx.setSuffix(_translate("AppFrame", " tm"))
        self.te_my.setSuffix(_translate("AppFrame", " tm"))
        self.te_lx.setSuffix(_translate("AppFrame", " m"))
        self.l_y.setText(_translate("AppFrame", "y"))
        self.l_x.setText(_translate("AppFrame", "x"))
        self.l_xy_ger.setText(_translate("AppFrame", "Gerilme"))
        self.btn_ger_xy_hesapla.setText(_translate("AppFrame", "Gerilme (x,y) Hesapla"))
        self.te_x.setSuffix(_translate("AppFrame", " m"))
        self.te_xy_ger.setSuffix(_translate("AppFrame", " t/m²"))
        self.te_y.setSuffix(_translate("AppFrame", " m"))
        self.btnHesapla.setText(_translate("AppFrame", "Hesapla"))
        self.btnDosyadanHesapla.setText(_translate("AppFrame", "Dosyadan Hesapla"))
        self.btnYardim.setText(_translate("AppFrame", "Yardım"))
        self.btnExit.setText(_translate("AppFrame", "Çıkış"))


import App_rc
